trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      curl -sSL https://install.python-poetry.org | python3 
      export PATH="$HOME/.local/bin:$PATH"  
      poetry config virtualenvs.in-project false
    displayName: 'Install Poetry'

  - script: |
      poetry install 
    displayName: 'Install dependencies'

  - script: |
      zip -r $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip src poetry.lock pyproject.toml
    displayName: 'Zip web app'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Subscription 1'
      appType: webAppLinux
      appName: python-azure-web-app
      resourceGroupName: ${{ parameters.resourceGroupName }}
      package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      deploymentMethod: zipDeploy
      startupCommand: python src/api/server.py